#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: ПроЛюбовь

# Short bio or description (displayed in the header)
description: Николай Воробьёв — Тренер по отношениям

# Slogan (displayed in the footer)
slogan: Тебе повезёт в любви!

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/12038933?v=3&s=200

image: "http://prolubov.tk/images/og-image.jpg"

#
# Flags below are optional
#

navigation:
- text: Блог
  url: /
- text: Ответы
  url: /ask/
  layout: answer
- text: Тренинг
  url: /tgo/
- text: Коучинг
  url: /coaching/
- text: Организаторам
  url: /org/
  layout: project
- text: Кто тут
  url: /about/

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: prolubov@prorealnost.com
  facebook: ProRealnost.ProLubov
  flickr:
  github:
  instagram: _prolubov
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: _ProLubov
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: proluboff

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-46456269-6

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://prolubov.tk

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# Какой проект yo содержит шоты для этого фронтенда
yo: prolubov
vk_app_id: 2264967
